# Generated by Django 4.2.23 on 2025-07-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("func", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="audio_file",
        ),
        migrations.AlterField(
            model_name="answer",
            name="transcript",
            field=models.TextField(default=""),
        ),
    ]
